### ISSUE TITLE
微调embedding环境报错

### ISSUE THREAD

**Issue by wilberlee** [percent4/embedding_model_exp#3]
请问在运行ft_embedding.py时，报如下错误是什么原因呢？python版本3.9，cuda版本11.2
```
Traceback (most recent call last):
  File "/root/autodl-tmp/embedding_model_exp/src/finetune/ft_embedding.py", line 58, in <module>
    args = SentenceTransformerTrainingArguments(
  File "<string>", line 133, in __init__
  File "/root/miniconda3/envs/e-finetune/lib/python3.9/site-packages/sentence_transformers/training_args.py", line 73, in __post_init__
    super().__post_init__()
  File "/root/miniconda3/envs/e-finetune/lib/python3.9/site-packages/transformers/training_args.py", line 1771, in __post_init__
    raise ValueError("--tf32 requires Ampere or a newer GPU arch, cuda>=11 and torch>=1.7")
ValueError: --tf32 requires Ampere or a newer GPU arch, cuda>=11 and torch>=1.7
```

**Comment by wilberlee** [comment]
找到原因了，TF32 仅支持 NVIDIA Ampere 架构或更新的 GPU，我用的T4不支持，`SentenceTransformerTrainingArguments`的参数tf32=False就可以了
